### ISSUE TITLE
[MiniShell Request] 

### ISSUE THREAD

**Issue by ObjectyGit** [coconutteamdev/minishell#6]
**Question 1**
How many "packages" can MiniShell handle on it's own?

**Feature Request**
There should be a supportive version for Windows & macOS. In my personal opinion, I don't think this program should be only for Linux applications.

**Question 3**
Will there be a better way to get help on MiniShell by asking the contributors?

**Question 4**
Is this going to be a different version of gitData (from the CinnamonTeam website)?

**Comment by actuallyexeon** [comment]
Mini shell is hard to be cross platform 😔. But we're trying are best on the wiki, if you stay updated you'll find support.

**Comment by datkat21** [comment]
I had a comment here but I lost it. Basically I said that MiniShell might work on Mac and I am working on a Windows version of MiniShell called MiniBatch because the Windows CMD programming language is Batch and not Bash (Linux shell programming language)
And for number 3 we are planning to add a bug report or feature request feature to MiniShell. 
Number 4, Maybe. We are focusing on CoconutApp and MiniShell first, though.+-
